stages:
  - test
  
lint_test:
  image: python:3.8.0-slim
  stage: test
  before_script:
    - pip install flake8-html
    - pip install Jinja2==3.0.1
  script:
    - flake8 --format=html --htmldir=flake_reports/
  artifacts:
    when: always
    paths:
      - flake_reports/